### ISSUE TITLE
Missing universities / tracking issue

### ISSUE THREAD

**Issue by theopolisme** [TreeHacks/root#146]
Need to add:

- [x] Universidad Abierta y a Distancia de México
- [x] California College of the Arts
- [x] Tecnológico de Saltillo
- [x] CUNY Queens College
- [x] Universidad Politécnica de Altamira

**Comment by theopolisme** [comment]
@jsutaria plz report here

**Comment by theopolisme** [comment]
@MYKatz can you go ahead and add this wave? I think it's enough of a critical mass 😉

**Comment by MYKatz** [comment]
@theopolisme 

done!
